### ISSUE TITLE
Bugreport: ext:dam_compat/1.3.3/README.rst is not rendered

### ISSUE THREAD

**Issue by marble** [xperseguers/TYPO3.docs.ter-automation#1]
**To reproduce:**

<pre>
# add to queue:
.../RENDER-DOC/force-render.sh dam_compat 1.3.3

# start rendering
/usr/bin/php  ..../Task/RenderTask.php
</pre>

**The problem is line 3:**

<pre>
(line1) [INFO] Processing dam_compat v.1.3.3
(line2) PHP Warning:  filesize(): stat failed for .../queue/dam_compat/1.3.3/README.md in .../Task/RenderTask.php on line 79
(line3) [WARNING] Unknown documentation format: skipping rendering
</pre>

Just from [looking at the code](https://github.com/xperseguers/TYPO3.docs.ter-automation/blob/master/Classes/Task/RenderTask.php#L79) I don't know what the problem is. The README.rst exists and I verified that it can be rendered.

**Comment by xperseguers** [comment]
got it
